#!/usr/bin/env php
<?php
ini_set("phar.readonly", "0");

$pharFile = './jnsc.phar';

if (file_exists($pharFile)) {
    unlink($pharFile);
}

$phar = new Phar('bin/jnsc.phar');
$phar->setSignatureAlgorithm(Phar::SHA1);

$phar->startBuffering();

$phar->addFile('src/index.php');
$phar->addFile('src/classmap.php');
$phar->addFile('src/Checker.php');

$phar->setStub(
    $phar->createDefaultStub('src/index.php', 'src/index.php')
);

$phar->stopBuffering();
